Squashed 'libretro/FBNeo/' changes from f84ac8a2f0..43058a5746
43058a5746 (libretro) update files
af48300970 Merge branch 'finalburnneo-master'
55a059bb00 Merge branch 'master' of https://github.com/finalburnneo/FBNeo into finalburnneo-master
8d2b60a16a burner/win32/neocdsel.cpp: allow for zipped cd cover and preview pngs
669394f6ba d_nes / d_sg1000 / d_snes: add 4 t-bra translations (#2563)
5da177108a add sega speech device (sp0250)
f268533e57 samples, add softstop option to channel stop
07f9065333 Merge branch 'master' of https://github.com/finalburnneo/FBNeo
e4c328b463 snes update from gab75
32d014e6d6 cps2: entirely remove sound gain
8d0c8b72ae (libretro) update files
7d1e41e6a8 Merge branch 'finalburnneo-master'
b145386cc2 Merge branch 'master' of https://github.com/finalburnneo/FBNeo into finalburnneo-master
6a1d2a6599 adj. in d_sms.cpp / d_snes.cpp ... (#2560)
9835286089 speccy update from gab75
3ea9df3464 win32/sel: Null the wild pointer
355b7368be app.rc: Remove whitespace
9cf981b367 win32: fix support paths UI
d8114d62a5 burner/win32/bzip.cpp: let user know about missing alternate bios file, instead of ambiguous can't start emulation error when alternate bios (unibios, etc) is selected in neogeo, for example
776ae71521 (libretro) update files
a6df2404a6 Merge branch 'finalburnneo-master'
d3e2566e3b Merge branch 'master' of https://github.com/finalburnneo/FBNeo into finalburnneo-master
ab56b9bb04 d_ngp.cpp: various... (#2559)
cbd6fc4be9 masters fury [iq_132]
e25f77b1fe dep/libs/dr_libs: update dr_libs
18bf848141 (libretro) better fix for subsets & pgm2
8ed9e0e00e Merge branch 'finalburnneo-master'
b9ec87a143 Merge branch 'master' of https://github.com/finalburnneo/FBNeo into finalburnneo-master
a16d1178e1 Add pgm2 memory card option (#1124)
58a95beb29 d_spectrum.cpp: updated the support to "Bloodstone (128K) (HB, v1.2)" (#2558)
827c81ceb5 gameinfo, controls -> cpanel
44d0b99068 Revert "Add pgm2 memory card option (#1123)"
a1ec93d8f4 Merge branch 'finalburnneo-master'
db2d6f24d7 Merge branch 'master' of https://github.com/finalburnneo/FBNeo into finalburnneo-master
d0661a228b d_cv1k.cpp: update description for matsuri15
6889f55190 (libretro) update files
60501e3697 Merge branch 'finalburnneo-master'
309bcd2b19 Merge branch 'master' of https://github.com/finalburnneo/FBNeo into finalburnneo-master
fda78b2d87 samples, fix issue checking channel status before sample plays for the first time
bb286e7c8d dtimer, add handy hz_to_cycles(), to get cycles from hz, clock
66cc93c931 speccy update from gab75
3eeec034f9 Add pgm2 memory card option (#1123)
f7574b86e0 (libretro) update files
b6f17b0a5a Merge branch 'finalburnneo-master'
d703b22664 Merge branch 'master' of https://github.com/finalburnneo/FBNeo into finalburnneo-master
ae30ed62b3 (libretro) mitigate RA bug
7de65478a3 samples.cpp/h: add BurnSampleChannelSetPlaybackRate(), fix BurnSampleGetChannelSample()
b92e383952 neogeo pocket: don't map power button to start (or anything) by default.  hitting it by accident is not fun
dbdd485d70 d_coleco.cpp, d_nes.cpp: various... (#2550)
9d7716aa20 (libretro) update files
abb049b2b5 Merge branch 'finalburnneo-master'
f19e49f132 Merge branch 'master' of https://github.com/finalburnneo/FBNeo into finalburnneo-master
7f8fdec04c d_nes: add chewchewm (#2549)
7aaf7053f4 famidash nes cfg
143412c405 d_nes: some changes in famidash... (#2548)
b8e16b03dd (libretro) update files
c59ee34890 Merge branch 'finalburnneo-master'
f1c3f297bf Merge branch 'master' of https://github.com/finalburnneo/FBNeo into finalburnneo-master
18f586563a pce: fix Champions Forever Boxing (USA)
1ddc6e0317 d_spectrum: mouselife2 (#2547)
94721b777a speccy update from gab75
af7e17ad99 pgm2 memcard possible fix
1d3567c0cd irem m62, fix ldrun4's dig effect (spritemask).  add drumkit to ldrun3 and 4
1de4d16162 d_snes: add 5 T-Bra translations (#2544)
0dfbf8d074 d_megadrive.cpp: updated "Ghost Baseball (HB, v2.0)" (#2545)
70554d7f8a d_pacman.cpp: add Man-Pac
2133aac400 (libretro) update files
6c233fd2cf Merge branch 'finalburnneo-master'
bc4d3bafef Merge branch 'master' of https://github.com/finalburnneo/FBNeo into finalburnneo-master
f067aae541 fbn win. ui: add -tpvalidate commandline option, to find missing titles and preview images via the titles and preview zip files
b4589b922b d_megadrive.cpp: adj. in bf3patdef (#2541)
ac837d0418 d_megadrive.cpp - add 'bk3defpat' (#2539)
a6c3db7d6b sms update from gab75
845fd7fde3 nes update from gab75
7034465fb7 megadrive update from gab75
97397961a8 d_coleco.cpp: various... (#2537)
a6f55868f1 update license.txt for kuba zip lib
be21229537 d_coleco.cpp: various... (#2536)
806cbc866c (libretro) update files
b064b1b521 Merge branch 'finalburnneo-master'
c792750a50 Merge branch 'master' of https://github.com/finalburnneo/FBNeo into finalburnneo-master
0ced32558f d_neogeo.cpp: updated "Shadow Gangs Zero (Backers Demo V1.0)" (#2534)
84594ea8c5 d_megadrive: add kidchampt (#2535)
7ec158ea8d game selector icons: speed up ~4x, support zipped icons
3659306f98 d_pce.cpp: added the support to "City Hunter (World)" (#2533)
e66740ad1c sms update from gab75
46f78d5976 (libretro) update files
814fb93106 Merge branch 'finalburnneo-master'
a09ec594f3 Merge branch 'master' of https://github.com/finalburnneo/FBNeo into finalburnneo-master
91308ee982 update msvc project for https://github.com/finalburnneo/FBNeo/commit/12c7863fff1df1a28e0d25809be66687b3562221
6f08789399 Merge branch 'master' of https://github.com/finalburnneo/FBNeo
c4dc8f6e36 gameinfo, bezel zip'd png support
50c91bc7da win32/ips_manager: fixed path
5d7e481d56 burner/win32/sel.cpp: zipped titles & previews support.  put titles.zip in support/titles.zip and previews.zip in support/previews.zip get the zips from here, and rename: fbn_titles.zip -> titles.zip fbn_previews.zip -> previews.zip
67135da0dd usb_sound_run -> usbsoundRun
e941ce0526 speccy update from gab75
07b76269f5 zip, dont use _s versions of wf*
ded5ddc3f6 d_megadrive.cpp: updated the support to "Ghost Baseball" v1.3 (#2531)
27a3171344 burner, image.cpp / image_win32.cpp: add PNGLoadBuffer(), PNGGetInfoBuffer(), PNGIsImageBuffer().  To load a png directly from memory
12c7863fff add kuba zip library from https://github.com/kuba--/zip
d68305089c d_pacman.cpp: updated "Chuckie Egg" to fix the missing lifts on level 4 (#2530)
8e96a4a385 (libretro) update files
345cd1a291 Merge branch 'finalburnneo-master'
813d505364 Merge branch 'master' of https://github.com/finalburnneo/FBNeo into finalburnneo-master
42d6f8dc51 d_neogeo: turfmastsc (#2529)
b21a468a41 d_ngp.cpp: added the support to "Jurl (HB)" (#2528)
6fb17372ea Added the support to 48 Inufuto's games (#2527)
67c30448c7 update msvc project for Atari System 1
53a6b1d6c8 (libretro) hook roadblst's pedal
5591a2324e (libretro) update files
fef1896a2a Merge branch 'finalburnneo-master'
d2ecbd596f Merge branch 'master' of https://github.com/finalburnneo/FBNeo into finalburnneo-master
abffa67a8c it's add new driver time!
e0f3155570 (libretro) update files
73c3660f77 Merge branch 'finalburnneo-master'
ca509dbd90 Merge branch 'master' of https://github.com/finalburnneo/FBNeo into finalburnneo-master
a2d3a5b7b0 d_alpha68k1.cpp: fix missing p3 up in paddlema
77be71b6d1 d_coleco.cpp, d_msx.cpp, d_sms.cpp, d_sg1000.cpp: rename "SwordWork" to "Sword Work" (#2525)
9adf0a771d speccy update from gab75
141fd9e9d0 SwordWork by Inufuto (#2524)
9abcc5dadb d_megadrive.cpp: more "Sacred Line" titles supported (#2523)
3c4d97f145 megadrive update from gab75
f3b23b4e54 Merge branch 'master' of https://github.com/finalburnneo/FBNeo
3a9d708316 nes update from gab75
09fff2b0c3 d_pgm2.cpp: differentiate tests/services keys
ef719cfa9b d_megadrive.cpp: various... (#2522)
9a73508979 (libretro) update files
9a0270781a Merge branch 'finalburnneo-master'
7d132028a1 Merge branch 'master' of https://github.com/finalburnneo/FBNeo into finalburnneo-master
9a77631065 d_neogeo.cpp: fix kof97plc
fcf8103c2a mushimallow fluff ver.1.5
a80f24320e d_megadrive.cpp, d_snes.cpp: various... (#2521)
cf67df8676 d_megadrive: wboymwpt (#2519)
4f708cca7d d_pce.cpp, d_snes.cpp: Shockman! (#2520)
08da79363a megadrive update from gab75
bb43c3f397 (libretro) update files
5d013fdedd Merge branch 'finalburnneo-master'
362b0f8308 Merge branch 'master' of https://github.com/finalburnneo/FBNeo into finalburnneo-master
40b5d189e0 sega system1, fix runahead issue with flicky
3d905bac12 burn_gun, check before draw
ef397ceeaf d_snes.cpp: added the support to "Rider's Spirits (World)" (#2518)
35b782e6d8 d_snes.cpp: those PAL games use the interlaced 512x478 mode
74b8b2e512 d_snes.cpp: only PAL has an interlaced 512x478 mode
5cd2221d04 (libretro) update files
2aa15589a7 Merge branch 'finalburnneo-master'
17a0c06715 Merge branch 'master' of https://github.com/finalburnneo/FBNeo into finalburnneo-master
96d9760820 d_pce.cpp: height should be 240
a696e1fd32 d_m62.cpp: height should be 248
167839b093 pgm2: implement socd
2c3b39edcf robotbwl and ripcord: hook up samples.  get samples: https://neo-source.com/index.php?topic=2487.msg39580#msg39580
5f5c33b1b0 Make "RETRO_ERROR_MESSAGES_12" be used correctly (#1119)
1baba537e6 (libretro) prevent reset on white error screen
99030db6bf (libretro) update files
4d3280e1df Merge branch 'finalburnneo-master'
2da0f22fda Merge branch 'master' of https://github.com/finalburnneo/FBNeo into finalburnneo-master
e1b240a195 d_megadrive.cpp: fix typos
ab654d08a2 hmm
04a847b731 Revert "d_megadrive.cpp: change default col mode draw for those games"
bd23644d7c (libretro) update chinese translation
327ace8428 (libretro) update files
1c93b11908 Merge branch 'finalburnneo-master'
45a50ff356 Merge branch 'master' of https://github.com/finalburnneo/FBNeo into finalburnneo-master
e0b7ce4dde d_megadrive.cpp: change default col mode draw for those games
c84eecf983 (libretro) update files
3705fa24b7 Merge branch 'finalburnneo-master'
73f69d6f36 Merge branch 'master' of https://github.com/finalburnneo/FBNeo into finalburnneo-master
e9ac8f4130 mcs48, add i8048 type to init
3ccc161d00 nes update from gab75
a83407be2a d_coleco.cpp: various... (#2512)
4a115ac9c7 (libretro) update files
686687535f Merge branch 'finalburnneo-master'
bae12f3289 Merge branch 'master' of https://github.com/finalburnneo/FBNeo into finalburnneo-master
5bc2b92db7 burn.cpp, rewind: don't block while repacking (fix hiccups with large rewind buffer during ffwd)
e02dd59253 d_neogeo: update kf2k1ult to 20260409, Thanks to Mr锅包肉
c0403046fa d_neogeo: add kof97ae230625, Thanks to gy8878736
5db893043d hamaway, stop scanning the wrong device..
e1bd634d0e gstrik2: remove broken roz layer message, this was fixed many moons ago
0fe93f6ed1 d_megadrive.cpp: added the support to "ZPF (Digital Edition) (HB)" (#2511)
98c7de062b neo_run.cpp: some additional comment about oc
5d4d04fa97 (libretro) update files
2e6e3888e9 Merge branch 'finalburnneo-master'
4c2182047b Merge branch 'master' of https://github.com/finalburnneo/FBNeo into finalburnneo-master
4274bfd9f9 Merge branch 'master' of https://github.com/finalburnneo/FBNeo
eeb23898c5 speccy update from gab75
e9235389ce (libretro) update files
54e7e9a1bd Merge branch 'finalburnneo-master'
5599240994 Merge branch 'master' of https://github.com/finalburnneo/FBNeo into finalburnneo-master
36ab7303a7 d_psikyo4.cpp: match default width with default single screen mode
643c9bd05f Merge branch 'finalburnneo-master'
1dbf264f1b Merge branch 'master' of https://github.com/finalburnneo/FBNeo into finalburnneo-master
7d3206a2ee tempest, oops
859302ac00 addendum
5dcfea5432 pgm2, improve determinism for recordings/netplay/etc
aad260ac2c (libretro) update files
8248420c1f Merge branch 'finalburnneo-master'
c7102a1544 Merge branch 'master' of https://github.com/finalburnneo/FBNeo into finalburnneo-master
eddfd2e512 Merge branch 'master' of https://github.com/finalburnneo/FBNeo
5ec7119fbf bezel, pgm2
600088b812 d_neogeo.cpp: let us play with lags !
e7be5990cb d_gaiden, clear the draw buffers when not drawing
ddf3aa6b2f d_neogeo: turfmastsc (#2509)
c5720f655c RomData: Fixed an issue where the manager did not clear the szRomdataNamevariable after loading the list
5778549d81 update jsa device
e869c6a203 (libretro) update files
9291e7536e Merge branch 'finalburnneo-master'
b5f3e43421 Merge branch 'master' of https://github.com/finalburnneo/FBNeo into finalburnneo-master
e5122551d5 (libretro) display version in logs
5b6a7af27d for all
ec9da3638a d_msx.cpp: added the support to "MSX Compilation Vols. 1 to 9" (about 150 games) (#2507)
a0c3b94f2a (libretro) update files
39fbab39cc Merge branch 'finalburnneo-master'
724ffe9008 Merge branch 'master' of https://github.com/finalburnneo/FBNeo into finalburnneo-master
f615bdfdf2 m68kcpu.c: fix MSVC error C2055
bab6618c56 Various... (#2506)
6e9a7717a3 (libretro) update files
f4ab405526 Merge branch 'finalburnneo-master'
6da4380cd6 Merge branch 'master' of https://github.com/finalburnneo/FBNeo into finalburnneo-master
98457238c3 pgm2_run: typo
87c1a81f74 pgm2: add an option for cardless mode to the dip settings
551072bcd8 Update pgm2_run.cpp (#2499)
395c416856 m68k, add insn callback
d06686e357 speccy update from gab75
0dd35e13f4 Fix the issue where a typo in creating a multilingual template causes the Eject state of the memory card to be displayed as the Insert state
b457d9bd91 d_pgm2.cpp: oops
ad973deb32 d_pgm2.cpp: refactor some rom definition
4572179b58 pgm2: avoid magic numbers
b674ac4643 d_snes.cpp: fix parenting/clone relation of knightsroundtp (#2504)
aa87fa108b d_snes: add 4 t-bra translations (#2503)
f5ffa1dcd4 d_pgm2.cpp: add serie flags
67fc150c03 (libretro) update files
fbcfec0771 Merge branch 'finalburnneo-master'
a0ef33966c Merge branch 'master' of https://github.com/finalburnneo/FBNeo into finalburnneo-master
cee40e5f4a d_pgm2.cpp: cleanup some redundancy and unneeded roms
cdb4bf7eb1 d_coleco.cpp: undo the rename of "Sword and Sorcerer (USA, Prototype)" (#2502)
915ea2e0c0 d_coleco.cpp: various... (#2501)
9ae2762a5d win32: Added multilingual template support for the PGM2 memory cards and the Re-Detect Controllers feature
cab26a1047 (libretro) update files
77de0d51b1 Merge branch 'finalburnneo-master'
77ce6b994b Merge branch 'master' of https://github.com/finalburnneo/FBNeo into finalburnneo-master
82f5790992 some changes in gami.cpp, md, pce... (#2500)
58d5b17df6 pgm2_run, improve state performance (rewind, runahead, state)
512e9f64ad arm9, add Arm9UnmapMemory() and Arm9BurnUntilInterrupt()
5a1bddfbd3 pgm2, support alternate speedhack for ddpdojt, improving performance for the game
77b4883e51 Some changes in... gami, d_neogeo, d_nes (#2498)
65422bca0f d_neogeo: add turfmastsc (#2497)
72aa7d73b9 update msvc project for pgm2
5731ae9b41 speccy update from gab75
71d56899ce (libretro) update files
0ae5c2c8d9 Merge branch 'finalburnneo-master'
a77f56321b Merge branch 'master' of https://github.com/finalburnneo/FBNeo into finalburnneo-master
9ac6558448 d_pgm2.cpp: cleanup kovnl oversea romsets
79a272728c burner/win32/romdata.cpp, export template dialog fixes: truncated initial filename, dialog title
b921ba0603 Merge branch 'master' of https://github.com/finalburnneo/FBNeo
e866379e89 RomData: Fix potential issue where RomData templates may fail to export to the desktop
f3790bfafe msx update from gab75
580ce1de4a (libretro) update files
72247ed6ce Merge branch 'finalburnneo-master'
9dd4613d14 Merge branch 'master' of https://github.com/finalburnneo/FBNeo into finalburnneo-master
fc8f5de2b6 update MSVC project & fix makefile
6348c167e5 Supports PGM2 games. (#2494)
72a34d883f d_pce.cpp - adj in necroste and more... (#2495)
fe9f5ed05c d_coleco.cpp: various... (#2493)
3456e50d07 update msvc project
f659af2c3b (libretro) update files
47baa3249e Merge branch 'finalburnneo-master'
c12636c657 Merge branch 'master' of https://github.com/finalburnneo/FBNeo into finalburnneo-master
eaa82e8772 d_coleco.cpp, d_nes.cpp, d_sms.cpp: various... (#2492)
53bd80e640 d_coleco.cpp: various... (#2491)
95842294b0 (libretro) update files
71fc8f1307 Merge branch 'finalburnneo-master'
9e747139c7 Merge branch 'master' of https://github.com/finalburnneo/FBNeo into finalburnneo-master
748fc9f0a1 nes, add Ignizol Combusts Literally Everything from https://captainpretzel.itch.io/ignizol-combusts-literally-everything
9912aabe17 d_nes.cpp: updated the support to "Trial of Kharzoid, The (HB, v1.4)" (#2489)
3a33619aae d_nes.cpp - adj. in kitty (#2490)
90d51fc5ec d_coleco.cpp: various... (#2488)
3cbee25d4b (libretro) update files
80086c06e8 Merge branch 'finalburnneo-master'
9d7a93d495 Merge branch 'master' of https://github.com/finalburnneo/FBNeo into finalburnneo-master
37ac03a8a3 d_coleco.cpp: various... (#2487)
294cc33b74 d_coleco.cpp: various... (#2486)
53e14645db some changes in megadrive, nes... (#2485)
7861c60572 nes update from gab75
50ca99206d d_dacholer, add service mode for itaten, dacholer, kickboy
d4ceb856d0 d_neogeo: samsho2pe (#2484)
ab97af449f nitedrvr,
988d131766 d_matmania.cpp: small cleanup
0c8b7ee926 matmania/maniach timings and vblank interval (#2483)
b6b44d9b16 d_nes.cpp, d_snes.cpp: various (#2482)
d1e764d35d Revert "sms update from gab75"
fcc56b8c93 sms update from gab75
c483fa375f Merge branch 'master' of https://github.com/finalburnneo/FBNeo
2738134c52 sms update from gab75
f489010fda d_sms.cpp: re-added the support to "Stella in Adventure World (GlobalHack)" (#2481)
ea06689f5b d_sms: atoms (#2480)
c332b39b60 sms update from gab75
7ad4906dcc d_megadrive: add sailormnpt (#2479)
6c84374c0e d_snes: add 4 t-bra translations (#2478)

git-subtree-dir: libretro/FBNeo
git-subtree-split: 43058a57464dd32a95ac0a0d139414d099cc55d6